### ISSUE TITLE
add compatibility with Ledger

### ISSUE THREAD

**Issue by landabaso** [bitcoinerlab/descriptors#10]
`parse` should also generate Ledger's Wallet policies and key information.

**Comment by 0xbrito** [comment]
I would love to take this one. FYI I'm kind of a newbie to bitcoin dev but I'm eager to provide some help to this project since I might be using this module.

**Comment by landabaso** [comment]
Discard this in favour of using ledgers' api.
A fork that can be installed with npm has been put here:
https://github.com/bitcoinerlab/ledger
