### ISSUE TITLE
Add new methods

### ISSUE THREAD

**Issue by landabaso** [bitcoinerlab/descriptors#11]
addSignatures([{pubKey:Buffer, signature:Buffer}])
addPreimages({"ripemd160(xxx)": preimage: Buffer})

getScriptSig() //FOR P2SH, P2SH-P2WSH, undefined otherwise
getScriptWitness() //FOR P2WSH, P2SH-P2WSH, undefined otherwise

getWitnessScript() //FOR P2WSH, P2SH-P2WSH, undefined otherwise
getRedeemScript() //For P2SH-P2WSH, P2SH, undefined otherwise
getLockTime();
getSequence();

**Comment by landabaso** [comment]
addPreimages({"<ripemd160_preimage(aaaa)>":"bbbbbbb"})

**Comment by 0xbrito** [comment]
Hi @landabaso  do you need some help?

**Comment by landabaso** [comment]
Hi @0xbrito,

Thank you for taking the time to offer help! At the moment, I am still in the process of deciding the API and refactoring the code, so it's not yet ready to accept contributions.

Once the code is in a more manageable state, there are plenty of tasks to do that I have in mind.

We keep in touch and thanks again!

**Comment by 0xbrito** [comment]
I see,

No worries! I'm still following this any update:)

**Comment by landabaso** [comment]
done
