### ISSUE TITLE
Support for `@scure/btc-signer`

### ISSUE THREAD

**Issue by heri16** [bitcoinerlab/descriptors#25]
Is there support for `@scure/btc-signer`

https://www.npmjs.com/package/@scure/btc-signer#bip174-psbt-multi-sig-example

`@scure/btc-signer` has been audited properly by an independent security firm, and with ~2600 lines of code, is meant to succeed `bitcoinjs-lib`.

**Comment by landabaso** [comment]
Hi @heri16 ! 
There is no support for @scure/btc-signer. This library in fact is highly tied to bitcoinjs-lib.
I'll keep an eye on it, though!

**Comment by landabaso** [comment]
Hey @heri16 , bitcoinerlab supports scure now!
